using UnrealBuildTool;

public class DayNight : ModuleRules {
    public DayNight(ReadOnlyTargetRules Target) : base(Target) {
        PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
        bLegacyPublicIncludePaths = false;
        ShadowVariableWarningLevel = WarningLevel.Warning;
        
        PublicDependencyModuleNames.AddRange(new string[] {
            "AIModule",
            "AkAudio",
            "AnimGraphRuntime",
            "AnimatedLights",
            "AnimationArchitectRuntime",
            "AnimationCore",
            "AudioMixer",
            "AvaAnimation",
            "AvaRenderTech",
            "BinkMediaPlayer",
            "CameraStack",
            "Chaos",
            "CinematicCamera",
            "ClothingSystemRuntimeCommon",
            "ClothingSystemRuntimeInterface",
            "ConsoleMacros",
            "ControlRig",
            "Core",
            "CoreUObject",
            "CustomizableCharacter",
            "DeveloperSettings",
            "Engine",
            "EnvironmentalGlobals",
            "ExposureConvert",
            "ExposureExpressions",
            "GameplayTags",
            "GameplayTasks",
            "GlobalLightRig",
            "InputCore",
            "Landscape",
            "LerpVolumes",
            "LevelSequence",
            "MaterialPermuter",
            "MediaAssets",
            "MediaUtils",
            "MovieScene",
            "MovieSceneTracks",
            "NavigationSystem",
            "Niagara",
            "NiagaraCore",
            "NiagaraHelpers",
            "NiagaraShader",
            "NiagaraStarField",
            "PhoenixSignificanceManager",
            "PhysicsCore",
            "ProceduralMeshComponent",
            "PropertyPath",
            "RenderSettings",
            "RigVM",
            "SceneRig",
            "SkinFX",
            "Slate",
            "SlateCore",
            "TimeRig",
            "UMG",
            "UtilitiesRuntime",
            "VolumetricClouds",
            "Weather",
        });
    }
}
