#pragma once
#include "CoreMinimal.h"
#include "ECalloutActions.generated.h"

UENUM(BlueprintType)
enum class ECalloutActions : uint8 {
    NOT_SET,
    Action_Interact,
    Action_Loot,
    Menu_Pickup,
    Action_Steal,
    Action_Open,
    Action_Close,
    Action_Locked,
    Action_Enter,
    Action_Join,
    Action_Use,
    Action_Search,
    Action_Sleep,
    Action_Place,
    Action_To,
    Action_ReadMail,
    Action_Sit,
    Action_PickPlant,
    Action_ForcePlant,
    Action_Empty,
    Action_Pet,
    ActionID_Water,
    ActionID_HarvestByproduct,
    Action_LightTorch,
    Action_WhisperPassword,
    Action_Exit,
    Action_TicklePear,
    Action_Collect,
    Action_Rotate,
    Action_Unlock,
    Action_Reveal,
    Action_Roll,
    Action_Travel,
    Action_Wait,
    Action_Begin,
    Action_StealthTakedown,
    Action_Identify,
    Action_Inspect,
    Action_Equip,
    Action_Investigate,
    Action_Start,
    Action_Invoke,
    Action_PlaceToken,
    Action_Talk,
    Action_View,
    Action_Read,
    Action_Dive,
    Action_ViewPensieve,
};

