#pragma once
#include "CoreMinimal.h"
#include "ActivityTypeIDs.generated.h"

UENUM(BlueprintType)
enum ActivityTypeIDs {
    ACTIVITY_TYPE_CLASS,
    ACTIVITY_TYPE_CLUB,
    ACTIVITY_TYPE_COMPANION,
    ACTIVITY_TYPE_EVENT,
    ACTIVITY_TYPE_EXCURSION,
    ACTIVITY_TYPE_FREETIME,
    ACTIVITY_TYPE_GUARD,
    ACTIVITY_TYPE_INVESTIGATE,
    ACTIVITY_TYPE_MEAL,
    ACTIVITY_TYPE_MINGLE,
    ACTIVITY_TYPE_MISSION,
    ACTIVITY_TYPE_MISSIONCRITICAL,
    ACTIVITY_TYPE_NURTURE,
    ACTIVITY_TYPE_OCCUPATION,
    ACTIVITY_TYPE_PATROL,
    ACTIVITY_TYPE_PERFORMTASK,
    ACTIVITY_TYPE_REST,
    ACTIVITY_TYPE_SEATFILLERSTATIC,
    ACTIVITY_TYPE_SELFSTUDY,
    ACTIVITY_TYPE_SLEEP,
    ACTIVITY_TYPE_TRANSIENTACTION,
    ACTIVITY_TYPE_COUNT,
    ACTIVITY_TYPE_MAX UMETA(Hidden),
};

