#pragma once
#include "CoreMinimal.h"
#include "BannerUpdateType.generated.h"

UENUM(BlueprintType)
enum BannerUpdateType {
    BANNER_UPDATE_NEW_MISSION,
    BANNER_UPDATE_MISSION_AVAILABLE,
    BANNER_UPDATE_MISSION_COMPLETE,
    BANNER_UPDATE_MISSION_ENDED,
    BANNER_UPDATE_MISSION_FAILED,
    BANNER_UPDATE_NEW_STEP,
    BANNER_UPDATE_STEP_COMPLETE,
    BANNER_UPDATE_STEP_UPDATED,
    BANNER_UPDATE_STEP_REDISPLAY,
    BANNER_UPDATE_NO_FOCUS_MISSION,
    BANNER_UPDATE_STEP_JOURNAL_UPDATED,
    BANNER_UPDATE_STEP_WAYPOINT,
    BANNER_UPDATE_SHOWMISSIONCOMPLETEUI,
    BANNER_UPDATE_NONE,
    BANNER_UPDATE_COUNT,
    BANNER_UPDATE_MAX UMETA(Hidden),
};

