#pragma once
#include "CoreMinimal.h"
#include "CollisionTypeIDs.generated.h"

UENUM(BlueprintType)
enum CollisionTypeIDs {
    STATION_COLLISION_GROUND,
    STATION_COLLISION_MOVING,
    STATION_COLLISION_SEATED,
    STATION_COLLISION_STANDING,
    STATION_COLLISION_STANDINGNOFORWARD,
    STATION_COLLISION_STANDINGNOFORWARD2P,
    STATION_COLLISION_STANDINGNOREVERSE,
    STATION_COLLISION_STANDINGWITHPROP,
    STATION_COLLISION_COUNT,
    STATION_COLLISION_MAX UMETA(Hidden),
};

