#pragma once
#include "CoreMinimal.h"
#include "EActivityTypeBits.generated.h"

UENUM(BlueprintType)
namespace EActivityTypeBits {
    enum Type {
        ACTIVITY_BIT_NONE,
        ACTIVITY_BIT_MISSION,
        ACTIVITY_BIT_MISSION_CRITICAL,
        ACTIVITY_BIT_EXCURSION = 0x4,
        ACTIVITY_BIT_HOBO = 0x8,
        ACTIVITY_BIT_INVESTIGATION = 0x10,
        ACTIVITY_BIT_PERFORM_TASK = 0x20,
        ACTIVITY_BIT_PERFORM_TASK_MOVETOLOCATION = 0x40,
        ACTIVITY_BIT_PERFORM_TASK_MOVETOSTATION = 0x80,
        ACTIVITY_BIT_PERFORM_TASK_WAITFORPLAYER = 0x100,
        ACTIVITY_BIT_PERFORM_TASK_CUSTOMNOLOCATIONTASK = 0x200,
        ACTIVITY_BIT_PERFORM_TASK_CUSTOMLOCATIONTASK = 0x400,
        ACTIVITY_BIT_PERFORM_TASK_TELEPORTTOSTATION = 0x800,
        ACTIVITY_BIT_PERFORM_TASK_TELEPORTCURTAINDOWN = 0x1000,
        ACTIVITY_BIT_PERFORM_TASK_FOLLOWACTOR = 0x2000,
        ACTIVITY_BIT_PERFORM_TASK_WAITFORTIME = 0x4000,
        ACTIVITY_BIT_PERFORM_TASK_NOP = 0x8000,
        ACTIVITY_BIT_HAIL = 0x10000,
        ACTIVITY_BIT_CLASS = 0x20000,
        ACTIVITY_BIT_PERFORM_TASK_APPARATEOUT = 0x40000,
        ACTIVITY_BIT_PERFORM_TASK_FOLLOWSCRIPTEDSPLINE = 0x80000,
        ACTIVITY_BIT_PERFORM_TASK_FOLLOWSPLINE = 0x100000,
        ACTIVITY_BIT_WANDER_AND_VANISH = 0x200000,
        ACTIVITY_BIT_WALK_AWAY_AND_RECYCLE = 0x200000,
        ACTIVITY_BIT_MAX UMETA(Hidden),
    };
}

