#pragma once
#include "CoreMinimal.h"
#include "EBeaconState.generated.h"

UENUM(BlueprintType)
enum class EBeaconState : uint8 {
    BEACONSTATE_NONE,
    BEACONSTATE_HIDDEN_BY_FOG_OF_WAR,
    BEACONSTATE_UNDISCOVERED_HIDDEN,
    BEACONSTATE_UNDISCOVERED,
    BEACONSTATE_DISCOVERED,
    BEACONSTATE_DISCOVERED_INCOMPLETE,
    BEACONSTATE_DISCOVERED_LOCKED,
    BEACONSTATE_DISCOVERED_UNLOCKED,
    BEACONSTATE_FAST_TRAVEL_LOCKED,
    BEACONSTATE_FAST_TRAVEL_UNLOCKED,
    BEACONSTATE_HANDLED_AT_RUNTIME,
    BEACONSTATE_COMPLETED,
    BEACONSTATE_MISSION_LEVEL_NOT_ENOUGH,
    BEACONSTATE_VENDOR_ACTIVE,
    BEACONSTATE_VENDOR_INACTIVE,
    BEACONSTATE_ICON_STACK,
    BEACONSTATE_MAX UMETA(Hidden),
};

