#pragma once
#include "CoreMinimal.h"
#include "EBeaconSubType.generated.h"

UENUM(BlueprintType)
enum class EBeaconSubType : uint8 {
    BEACONSUBTYPE_NONE,
    BEACONSUBTYPE_CHEST_DEFAULT,
    BEACONSUBTYPE_CHEST_TRACKED,
    BEACONSUBTYPE_CHEST_LOOTABLE,
    BEACONSUBTYPE_BEASTDEN_DIRICAWL,
    BEACONSUBTYPE_BEASTDEN_FWOOPER,
    BEACONSUBTYPE_BEASTDEN_GIANTPURPLETOAD,
    BEACONSUBTYPE_BEASTDEN_GRAPHORN,
    BEACONSUBTYPE_BEASTDEN_HIPPOGRIFF,
    BEACONSUBTYPE_BEASTDEN_JOBBERKNOLL,
    BEACONSUBTYPE_BEASTDEN_KNEAZLE,
    BEACONSUBTYPE_BEASTDEN_MOONCALF,
    BEACONSUBTYPE_BEASTDEN_NIFFLER,
    BEACONSUBTYPE_BEASTDEN_PUFFSKEIN,
    BEACONSUBTYPE_BEASTDEN_THESTRAL,
    BEACONSUBTYPE_BEASTDEN_UNICORN,
    BEACONSUBTYPE_COMBATCHALLENGE_PLAYSTATION,
    BEACONSUBTYPE_MAX UMETA(Hidden),
};

