#pragma once
#include "CoreMinimal.h"
#include "EEnemyAIAnimState.generated.h"

UENUM(BlueprintType)
enum class EEnemyAIAnimState : uint8 {
    Idle,
    IdleReady,
    Moving,
    Spawn,
    Attack,
    BecomeAware,
    LoseAware,
    ActivateStoredWeapon,
    StoreActiveWeapon,
    PickupWeaponFloor,
    PickupWeaponWall,
    PickupWeapon,
    DodgeLeft,
    DodgeRight,
    Dodge,
    Disappear_DEPRECATED,
    Reappear_DEPRECATED,
    Taunt,
    Land,
    TurnInPlace,
    Shuffle,
    FleeExit,
    MovingRunTo,
    React,
    NurtureInteract_DEPRECATED,
    Eat_DEPRECATED,
    Jump,
    Dead,
    Climb,
    IdleBreak,
    BecomeAlert,
    LoseAlert,
    Apparate,
    Flourish,
    Flying,
    StartDrained,
    StopDrained,
    Drained,
    AlertWait,
    AlertLook,
    JumpSpline,
};

