#pragma once
#include "CoreMinimal.h"
#include "EEnemy_BBKey.generated.h"

UENUM(BlueprintType)
enum class EEnemy_BBKey : uint8 {
    None,
    Spawn,
    Dodge,
    BecomeAware,
    LoseAware,
    LosingTarget,
    DEPRECATED_SeekingWeapon,
    Lumos,
    React,
    StoreActiveWeapon,
    ActivateWeapon,
    Scared,
    Investigate,
    Jump,
    Abort,
    GameEvent,
    DEPRECATED_ScheduledEntity,
    Climb,
    Protego,
    SecondaryAttack,
    ClimbLadder,
    BecomeAlert,
    LoseAlert,
    HealAttack,
    InvestigateAlert,
    Disillusionment,
    ReparoAttack,
    Vault,
    CustomPause,
    SidekickAttack,
    ProtegoStart,
    Alert,
    SwimToShore,
    Outside,
    TooCloseToNPC,
    JumpSpline,
    BackOnNav,
    RecoverWeapon,
    Aggro,
    TASTreeState,
    SpellEffect,
    AwareTurnAround,
    AwarePause,
    EEnemy_MAX UMETA(Hidden),
};

