#pragma once
#include "CoreMinimal.h"
#include "EEnemy_AttackUpdateState.generated.h"

UENUM(BlueprintType)
enum class EEnemy_AttackUpdateState : uint8 {
    None,
    Init,
    Moving,
    Paused,
    StartFace,
    Face,
    StopMove,
    StoppingMove,
    Taunt,
    Shuffle,
    Attack,
    TauntAttack,
    Cover,
    StartReady,
    PickupWeapon,
    StoreActiveWeapon,
    FaceWeapon,
    Ready,
    Apperate,
    CheckRetreat,
    FaceLoc,
    Stunned,
    Jump,
    IdleBreak,
    StartMove,
    UpdateMove,
    StartAttack,
    StartRetreat,
    StopRetreat,
    Retreating,
    StoppingRetreat,
    Flourish,
    Protego,
    StartDrained,
    Drained,
    StopDrained,
    Equip,
    CounterAttack,
    StartMoveWait,
    Count,
    EEnemy_MAX UMETA(Hidden),
};

