#pragma once
#include "CoreMinimal.h"
#include "EFieldGuideExitReasons.generated.h"

UENUM(BlueprintType)
enum EFieldGuideExitReasons {
    FIELD_GUIDE_EXIT_REASON_NONE,
    FIELD_GUIDE_EXIT_REASON_BACK_TO_GAME,
    FIELD_GUIDE_EXIT_REASON_BACK_TO_GAME_FROM_MAP,
    FIELD_GUIDE_EXIT_REASON_LOAD_GAME,
    FIELD_GUIDE_EXIT_REASON_RESTART_FROM_LAST_SAVE,
    FIELD_GUIDE_EXIT_REASON_EXIT_TO_MAIN,
    FIELD_GUIDE_EXIT_REASON_EXIT_TO_MAIN_GAME_OVER,
    FIELD_GUIDE_EXIT_REASON_QUIT_GAME,
    FIELD_GUIDE_EXIT_REASON_FAST_TRAVEL_FROM_MAP,
    FIELD_GUIDE_EXIT_REASON_HOVER_DRONE,
    FIELD_GUIDE_EXIT_REASON_FAST_TRAVEL_FROM_IMGUI,
    FIELD_GUIDE_EXIT_REASON_ABANDON_QUEST_FROM_QUEST_LOG,
    FIELD_GUIDE_EXIT_REASON_ABANDON_QUEST_FROM_GAME_OVER,
    FIELD_GUIDE_EXIT_REASON_MAX UMETA(Hidden),
};

