#pragma once
#include "CoreMinimal.h"
#include "EFieldGuideExitStates.generated.h"

UENUM(BlueprintType)
enum EFieldGuideExitStates {
    FIELD_GUIDE_EXIT_STATE_NONE,
    FIELD_GUIDE_EXIT_STATE_FADING_IN,
    FIELD_GUIDE_EXIT_STATE_FADING_OUT,
    FIELD_GUIDE_EXIT_STATE_SPIN_ON_BLANK,
    FIELD_GUIDE_EXIT_STATE_DELAY,
    FIELD_GUIDE_EXIT_STATE_UNLOAD_FIELD_GUIDE,
    FIELD_GUIDE_EXIT_STATE_NO_FADE,
    FIELD_GUIDE_EXIT_STATE_RESTART_FROM_LAST_SAVE,
    FIELD_GUIDE_EXIT_STATE_LOAD_GAME,
    FIELD_GUIDE_EXIT_STATE_EXIT_TO_MAIN,
    FIELD_GUIDE_EXIT_STATE_EXIT_TO_MAIN_GAME_OVER,
    FIELD_GUIDE_EXIT_STATE_HOVER_DRONE,
    FIELD_GUIDE_EXIT_STATE_FAST_TRAVEL_FROM_MAP,
    FIELD_GUIDE_EXIT_STATE_FAST_TRAVEL_FROM_IMGUI,
    FIELD_GUIDE_EXIT_STATE_ABANDON_QUEST_FROM_QUEST_LOG,
    FIELD_GUIDE_EXIT_STATE_ABANDON_QUEST_FROM_GAME_OVER,
    FIELD_GUIDE_EXIT_STATE_HOLD_FADE,
    FIELD_GUIDE_EXIT_STATE_MAX UMETA(Hidden),
};

