#pragma once
#include "CoreMinimal.h"
#include "EHomeworkType.generated.h"

UENUM(BlueprintType)
enum EHomeworkType {
    HOMEWORK_TYPE_SPELL_CAST,
    HOMEWORK_TYPE_SPELL_SUCCESS,
    HOMEWORK_TYPE_POTION,
    HOMEWORK_TYPE_POTION_CONSUMED,
    HOMEWORK_TYPE_SANCTUARY_USE,
    HOMEWORK_TYPE_PLANT,
    HOMEWORK_TYPE_BEAST,
    HOMEWORK_TYPE_COMPANION_MINUTES,
    HOMEWORK_TYPE_BROOM,
    HOMEWORK_TYPE_COMBAT,
    HOMEWORK_TYPE_COLLECT,
    HOMEWORK_TYPE_INVESTIGATE,
    HOMEWORK_TYPE_MISC,
    HOMEWORK_TYPE_CONJURATION,
    HOMEWORK_TYPE_COUNT,
    HOMEWORK_TYPE_MAX UMETA(Hidden),
};

