#pragma once
#include "CoreMinimal.h"
#include "EKnowledgeAction.generated.h"

UENUM(BlueprintType)
enum EKnowledgeAction {
    AstronomyAltar,
    BeastCaptured,
    BreedingAssigned,
    BrewPotion,
    CalloutReference,
    Collect,
    Conjure,
    ConversationReference,
    ConversationReward,
    CraftTrait,
    Damaged,
    DemiguiseStatue,
    Discover,
    DuelTechniqueCompleted,
    GatherBeastByproduct,
    GatherPlant,
    HappinessFromFeed,
    HappinessFromPetting,
    HappinessFromPlaying,
    Interact,
    Investigation,
    Killed,
    Mission,
    MissionDayOne,
    MissionJumbo,
    MissionLarge,
    MissionMedium,
    MissionSmall,
    Perceived,
    Received,
    SocialConversation,
    SocialGiveGift,
    SpellCast,
    TutorialUnlock,
    UseFertilizer,
    NamedEnemyKilled,
    HouseChestOpened,
    GoldChestOpened,
    AncientMagicHotSpot,
    MerlinTrialCompleted,
    RecipeLearned,
    UpgradeStats,
};

