#pragma once
#include "CoreMinimal.h"
#include "EMapToolTipTypes.generated.h"

UENUM(BlueprintType)
enum class EMapToolTipTypes : uint8 {
    MAP_TOOL_TIP_TYPE_UNSET,
    MAP_TOOL_TIP_TYPE_DUNGEON,
    MAP_TOOL_TIP_TYPE_FAST_TRAVEL,
    MAP_TOOL_TIP_TYPE_CASTLE,
    MAP_TOOL_TIP_TYPE_HAMLET,
    MAP_TOOL_TIP_TYPE_BANDIT_CAMP,
    MAP_TOOL_TIP_TYPE_WAY_MARKER,
    MAP_TOOL_TIP_TYPE_PLAYER_MARKER,
    MAP_TOOL_TIP_TYPE_FILTER_REGION,
    MAP_TOOL_TIP_TYPE_HOGWARTS,
    MAP_TOOL_TIP_TYPE_HOGSMEADE,
    MAP_TOOL_TIP_TYPE_ENEMY_LOCATION,
    MAP_TOOL_TIP_TYPE_MISSION,
    MAP_TOOL_TIP_TYPE_STACK,
    MAP_TOOL_TIP_TYPE_MAX UMETA(Hidden),
};

