#pragma once
#include "CoreMinimal.h"
#include "EMapIconState.generated.h"

UENUM(BlueprintType)
enum EMapIconState {
    MAP_ICON_STATE_HOVER,
    MAP_ICON_STATE_FT_PULSE,
    MAP_ICON_STATE_PLAYER_BOUNCE,
    MAP_ICON_STATE_NEWLY_DISCOVERED,
    MAP_ICON_STATE_NEAREST_FT,
    MAP_ICON_STATE_STOP_ANIMATION,
    MAP_ICON_STATE_STOP_ANIMATION_POSITION_ONLY,
    MAP_ICON_STATE_STOP_ANIMATION_SCALE_ONLY,
    MAP_ICON_STATE_IDLE,
    MAP_ICON_STATE_INVALID,
    MAP_ICON_STATE_MAX UMETA(Hidden),
};

