#pragma once
#include "CoreMinimal.h"
#include "EMapInstanceIconType.generated.h"

UENUM(BlueprintType)
enum EMapInstanceIconType {
    MAP_INSTANCE_ICON_TYPE_NONE,
    MAP_INSTANCE_ICON_TYPE_ICON,
    MAP_INSTANCE_ICON_TYPE_PERCEPTION,
    MAP_INSTANCE_ICON_TYPE_AREA_BEACON_CIRCLE,
    MAP_INSTANCE_ICON_TYPE_AREA_BEACON_ICON,
    MAP_INSTANCE_ICON_TYPE_AREA_BEACON_OUTLINE,
    MAP_INSTANCE_ICON_TYPE_PATH,
    MAP_INSTANCE_ICON_TYPE_AUTHORITY,
    MAP_INSTANCE_ICON_TYPE_ACCESSIBILITY_AUDIO_CUE = 0x9,
    MAP_INSTANCE_ICON_TYPE_ACCESSIBILITY_EFFECT = 0x9,
    MAP_INSTANCE_ICON_TYPE_ENEMY,
    MAP_INSTANCE_ICON_TYPE_MAX UMETA(Hidden),
};

