#pragma once
#include "CoreMinimal.h"
#include "ENPC_Mobility.generated.h"

UENUM(BlueprintType)
enum class ENPC_Mobility : uint8 {
    None,
    Default,
    Attack,
    Pressure,
    Far,
    RunTo,
    Wander,
    Scared,
    Flee,
    Cover,
    Close,
    Evade,
    SeekWeapon,
    Dynamic,
    DynamicTarget,
    DynamicSprint,
    ScheduledEntity,
    FollowPlayer,
    Swim,
    Crouch,
    OnFire,
    Charred,
    Crouching,
    UpStairs,
    DownStairs,
    UpSlope,
    DownSlope,
    Retreat,
    RunToNear,
    RetreatSplit,
    CombatWalk,
    CombatJog,
    CombatRun,
    CharredRunTo,
    TooClose,
    Alert,
    Outside,
    Stealth,
    BackOnNav,
    Charge,
    RecoverWeapon,
    PointOfInterest,
    Override,
    Count,
    ENPC_MAX UMETA(Hidden),
};

