#pragma once
#include "CoreMinimal.h"
#include "ENPC_TargetSelectionWeightData.generated.h"

UENUM(BlueprintType)
enum class ENPC_TargetSelectionWeightData : uint8 {
    DistNearWeight,
    DistFarWeight,
    DistNear,
    DistFar,
    MaintainTargetWeight,
    MaintainTargetFalloff,
    TargetWeight,
    LargeCharacterWeight,
    NumAttackingMultWeight,
    StayInWeight,
    RecentlyAttackedByWeight,
    RecentlyAttackedByFalloff,
    RecentlyAttackedByPlayerWeight,
    RecentlyAttackedByPlayerFalloff,
    HighlightedByPlayerWeight,
    AttackingWeight,
    RecentlyAttackedTargetWeight,
    RecentlyAttackedTargetFalloff,
    RecentlyAttackedPlayerWeight,
    RecentlyAttackedPlayerFalloff,
    ReactingIncMultWeight,
    ReactingTimePeak,
    ReactingDecMultWeight,
    InCCReactionWeight,
    InKnockDownWeight,
    InRagDollWeight,
    InAirWeight,
    InCriticalHealthWeight,
    InNearDeathKneelingWeight,
    ShielsOnWeight,
    LevelMultWeight,
    LevelMinWeight,
    LevelMaxWeight,
    HealthMultWeight,
    HealthMinWeight,
    HealthMaxWeight,
    ThreatMultWeight,
    ThreatMinWeight,
    ThreatMaxWeight,
    SpiderOnFireWeight,
    InferiusOnFireWeight,
    InferiusKamikazeWeight,
    Count,
    ENPC_MAX UMETA(Hidden),
};

