#pragma once
#include "CoreMinimal.h"
#include "ENPC_SelectionStates.generated.h"

UENUM(BlueprintType)
enum class ENPC_SelectionStates : uint8 {
    None,
    Arrested,
    Attacking,
    Confounded,
    Crucioed,
    Cursed,
    DistanceHigh,
    DistanceMed,
    DistanceLow,
    Enchanted,
    Enraged,
    Flying,
    Frozen,
    HealthHigh,
    HealthMed,
    HealthLow,
    HealthCritical,
    Imperiused,
    InAir,
    InCCReaction,
    InKnockDown,
    InRadiusHigh,
    InRadiusMed,
    InRadiusLow,
    InRagDoll,
    InReaction,
    InReactionMax,
    InReactionLong,
    InReactionMed,
    InReactionShort,
    IsInferi,
    IsSpider,
    IsSpiderCrit,
    LargeCharacter,
    Levitated,
    NotCursed,
    NotInReaction,
    OnFire,
    OnGround,
    Petrified,
    RemainingHigh,
    RemainingMed,
    RemainingLow,
    Shielding,
    Stupefy1,
    Stupefy2,
    Stupefy3,
    Stupefy4,
    Swimming,
    ThreatMax,
    ThreatHigh,
    ThreatMed,
    ThreatLow,
    HitsTaken,
    TimeSinceLastAction,
    RecentlyAttackedByPlayer,
    HighLightedByPlayer,
    RecentlyAttackedPlayer,
    InNearDeathKneeling,
    SpiderOnFire,
    InferiusOnFire,
    InferiusKamikaze,
    Count,
    ENPC_MAX UMETA(Hidden),
};

