#pragma once
#include "CoreMinimal.h"
#include "EStationInteraction.generated.h"

UENUM(BlueprintType)
enum class EStationInteraction : uint8 {
    STATION_INTERACTION_CURRENT_NONE,
    STATION_INTERACTION_CURRENT_ENTERING,
    STATION_INTERACTION_CURRENT_INSIDE,
    STATION_INTERACTION_CURRENT_EXITING,
    STATION_INTERACTION_DESIRED_NONE,
    STATION_INTERACTION_DESIRED_ENTER,
    STATION_INTERACTION_DESIRED_ENTER_NOW,
    STATION_INTERACTION_DESIRED_EXIT,
    STATION_INTERACTION_DESIRED_EXITNOW,
    STATION_INTERACTION_DESIRED_AUTO_EXIT,
    STATION_INTERACTION_MAIL_START,
    STATION_INTERACTION_MAIL_END,
    STATION_INTERACTION_MISSION_START,
    STATION_INTERACTION_MISSION_END,
    STATION_INTERACTION_MAX UMETA(Hidden),
};

