#pragma once
#include "CoreMinimal.h"
#include "SocialSemanticTypeIDs.generated.h"

UENUM(BlueprintType)
enum SocialSemanticTypeIDs {
    SOCIAL_SEMANTIC_TYPE_DEPRECATED,
    SOCIAL_SEMANTIC_TYPE_EMOTION,
    SOCIAL_SEMANTIC_TYPE_FACTION,
    SOCIAL_SEMANTIC_TYPE_IDENTITY,
    SOCIAL_SEMANTIC_TYPE_INTEREST,
    SOCIAL_SEMANTIC_TYPE_PERSONALITY,
    SOCIAL_SEMANTIC_TYPE_TRAIT,
    SOCIAL_SEMANTIC_TYPE_COUNT,
    SOCIAL_SEMANTIC_TYPE_MAX UMETA(Hidden),
};

