#pragma once
#include "CoreMinimal.h"
#include "SocialInteractionTypeIDs.generated.h"

UENUM(BlueprintType)
enum SocialInteractionTypeIDs {
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_COMPANION,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_CURRICULUM,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_EXIT,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_EXTORT,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_FACTSHEET,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_FAVOR,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_GIFT,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_MISSION,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_RELATIONSHIP,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_SANCEXPANSION,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_SCAVENGERHUNT,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_TEAGUEINVENTORY,
    SOCIAL_INTERACTION_TYPE_ICON_INTERACTTYPE_VENDOR,
    SOCIAL_INTERACTION_TYPE_NONE,
    SOCIAL_INTERACTION_TYPE_COUNT,
    SOCIAL_INTERACTION_TYPE_MAX UMETA(Hidden),
};

